# Generated by Django 5.2.4 on 2025-08-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок', max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, help_text='Тут должен быть текст вашей статьи', null=True, verbose_name='Содержимое')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение для превью', null=True, upload_to='images/', verbose_name='Превью')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите стоимость товара', max_digits=11, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True, help_text='Укажите, была ли статья опубликована', verbose_name='Признак публикации')),
                ('views_counter', models.PositiveIntegerField(verbose_name='Счетчик просмотров')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ['created_at'],
            },
        ),
    ]
