# Generated by Django 5.2.4 on 2025-08-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='price',
        ),
    ]
