# Generated by Django 5.2.4 on 2025-08-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='views_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Счетчик просмотров'),
        ),
    ]
