# Generated by Django 5.2.4 on 2025-08-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='Введите страну', max_length=50, verbose_name='Страна')),
                ('tin', models.CharField(help_text='Введите ИНН', max_length=50, verbose_name='ИНН')),
                ('address', models.TextField(help_text='Введите адрес', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
                'ordering': ['country'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Введите наименование категории', max_length=100, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Введите наименование товара', max_length=150, verbose_name='Наименование товара'),
        ),
    ]
