# Generated by Django 5.2.4 on 2025-08-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_created_at_alter_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Укажите, есть ли товар в наличии', verbose_name='Наличие товара'),
        ),
    ]
