# Generated by Django 5.2.4 on 2025-09-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_is_published_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['country'], 'permissions': [('can_unpublish_product', 'can unpublish product')], 'verbose_name': 'контакт', 'verbose_name_plural': 'контакты'},
        ),
    ]
